### ISSUE TITLE
Quick citation

### ISSUE THREAD

**Issue by joerobmunoz** [Daniel-R-Armstrong/French-Wiki-2500-Pretrained-SentencePiece-LM#1]
Hey,

Thanks again for making your work available. Do you have a citation for the following quote?

> Based on the research from fast.ai a more accurate language model doesn't necessarily mean you will have a better classifier, and often the opposite is true.

I've heard it referenced in the lectures, but haven't been able to find the source.

Thanks!

**Comment by danacity** [comment]
I think my citation might be a little out of context. If you are looking for the video were Jeremy talks about it, here is the link: https://www.youtube.com/watch?v=MDX_x6rKXAs&feature=youtu.be&t==23
It is referring more to the benefit of increasing dropout in the awd-lstm.
